<?php
header("Cache-Control: no-cache, must-revalidate");
header("Expires: Mon, 26 Jul 1997 05:00:00 GMT");
ini_set('session.gc_maxlifetime',3*60*60);
ini_set('date.timezone', 'America/New_York');
ini_set('mysql.connect_timeout', 600);
ini_set('default_socket_timeout', 600);
ini_set ( 'register_globals' , 'On' );
session_start();
require_once 'helpers/configure.php';
require_once 'helpers/functions.php';
require_once 'library/smtp.php';
require_once 'library/phpmailer.php';
require_once 'library/Api.php';
require_once 'library/Drewm/MailChimp.php';
require_once 'library/MigException.php';
require_once 'library/cssfile.php';
require_once 'library/csv_create.php';
require_once 'library/shopify.php';
require_once 'library/pagination.php';
require_once 'dao/connection.php';
require_once 'dao/admin_dao.php';
require_once 'dao/customerdao.php';
require_once 'dao/cronjob_dao.php';
require_once 'dao/mailchimp_dao.php';
require_once 'dao/manager_dao.php';
require_once 'dao/payment_stat_dao.php';
require_once 'model/mailchimp.php';
require_once 'model/mail.php';
require_once 'model/orders.php';
require_once 'model/products.php';
require_once 'model/user.php';
require_once 'model/template.php';
require_once 'controller/login.php';
require_once 'controller/mailchimpC.php';
require_once 'controller/bigcommerce_products.php';
require_once 'controller/customer.php';
require_once 'controller/cronjob.php';
require_once 'controller/admin.php';
require_once 'controller/popup.php';
require_once 'controller/contact.php';
require_once 'controller/manager.php';
require_once 'controller/payment_stat.php';